import Head from "next/head";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import fetcher from "../utils/fetcher";

export default function Home() {
  const { data, error } = useSWR("/api/hello", fetcher);

  const renderMessage = () => {
    if (error) return "Failed to load";
    if (!data) return "Loading...";

    return data.message;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{renderMessage()}</h1>
      </main>
    </div>
  );
}
